name: CatsKit
description: "A new Flutter project."
publish_to: 'none'

# ========== 版本号 ==========
# 格式: versionName+versionCode
# 1.0.0 是用户看到的版本名称
# 2 是内部版本号，每次上架必须递增
version: 0.6.0+22

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.16.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ========== 添加图标生成插件 ==========
  flutter_launcher_icons: ^0.14.3

# ========== 图标配置 ==========
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true

  # ========== 添加资源目录 ==========
  assets:
    - assets/icon/icon.jpg
    - assets/ocr/catskit_ocr.py
    - assets/images/