/// 完整 Navimoe 数据模型
/// 参考: https://github.com/SAK-20744/Navimoe
library;

// ========== 稀有度 ==========
enum Rarity { r1, r2, r3, r4, r5, r6 }

int maxLevelForRarity(Rarity r) => r == Rarity.r6 ? 18 : 20;

// ========== 分类 ==========
enum PartCategory { body, weapon, wheel, gadget }

// ========== 武器/装置分类 ==========
enum PartClass { none, melee, ranged, autoAim, minion, special }

// ========== 赞助商 ==========
enum Sponsor { none, mecha, naturalis, gluttony, sporty }

// ========== 属性增长模式 (SIP) ==========
enum StatsIncrementPattern { r1, r2, r3, r4, r5, r6, r6Legacy }

/// 根据 SIP 和等级计算最终属性值
double mapToLevel(double base, int level, StatsIncrementPattern sip) {
  if (level <= 1) return base;
  final maxLv =
      sip == StatsIncrementPattern.r6 || sip == StatsIncrementPattern.r6Legacy
      ? 18
      : 20;
  if (level > maxLv) level = maxLv;

  double result = base;
  if (sip == StatsIncrementPattern.r6Legacy) {
    double delta = result * 0.19163;
    for (int i = 2; i <= level; i++) {
      result += delta;
      delta += result / 15;
    }
  } else {
    for (int i = 2; i <= level && i <= 16; i++) {
      result = (result * 1.2).floorToDouble();
    }
    if (level >= 17) {
      final fixedDelta = ((result * 0.0875) - 1).floorToDouble();
      result += fixedDelta * (level - 16);
    }
  }
  return result;
}

// ========== 加成 ==========
class BonusData {
  final PartCategory category;
  final int percent;
  const BonusData(this.category, this.percent);
}

// ========== 插槽 ==========
class SlotData {
  final int weapon;
  final int wheel;
  final int gadget;
  const SlotData(this.weapon, this.wheel, this.gadget);
}

// ========== 部件数据 ==========
class PartData {
  final String id;
  final String name;
  final String nameZh;
  final String nameJa;
  final PartCategory category;
  final Rarity rarity;
  final PartClass partClass;
  final Sponsor sponsor;
  final int hp1;
  final int atk1;
  final int mHp1;
  final int power;
  final BonusData? bonus;
  final SlotData? slots;
  final StatsIncrementPattern sip;

  const PartData({
    required this.id,
    required this.name,
    this.nameZh = '',
    this.nameJa = '',
    required this.category,
    required this.rarity,
    this.partClass = PartClass.none,
    this.sponsor = Sponsor.none,
    this.hp1 = 0,
    this.atk1 = 0,
    this.mHp1 = 0,
    this.power = 0,
    this.bonus,
    this.slots,
    this.sip = StatsIncrementPattern.r1,
  });

  int get maxLevel => maxLevelForRarity(rarity);
  double hp(int level) => mapToLevel(hp1.toDouble(), level, sip);
  double atk(int level) => mapToLevel(atk1.toDouble(), level, sip);
  double get hpMax => hp(maxLevel);
  double get atkMax => atk(maxLevel);
  double mHp(int level) {
    final s = sip == StatsIncrementPattern.r6Legacy
        ? StatsIncrementPattern.r6
        : sip;
    return mapToLevel(mHp1.toDouble(), level, s);
  }

  String get categoryLabel {
    switch (category) {
      case PartCategory.body:
        return '车身';
      case PartCategory.weapon:
        return '武器';
      case PartCategory.wheel:
        return '车轮';
      case PartCategory.gadget:
        return '配件';
    }
  }

  String get rarityLabel => rarity.name.toUpperCase();

  String get sponsorLabel {
    switch (sponsor) {
      case Sponsor.none:
        return '';
      case Sponsor.mecha:
        return 'Mecha Corp';
      case Sponsor.naturalis:
        return 'Naturalis Inc';
      case Sponsor.gluttony:
        return 'Gluttony Ltd';
      case Sponsor.sporty:
        return 'Sporty LLC';
    }
  }

  String get classLabel {
    switch (partClass) {
      case PartClass.none:
        return '';
      case PartClass.melee:
        return '近战';
      case PartClass.ranged:
        return '远程';
      case PartClass.autoAim:
        return '自动瞄准';
      case PartClass.minion:
        return '随从';
      case PartClass.special:
        return '特殊';
    }
  }

  String get slotsLabel {
    if (slots == null) return '';
    return '武${slots!.weapon} 轮${slots!.wheel} 配${slots!.gadget}';
  }

  String get bonusLabel {
    if (bonus == null) return '';
    final cat = bonus!.category == PartCategory.body
        ? '车身'
        : bonus!.category == PartCategory.weapon
        ? '武器'
        : bonus!.category == PartCategory.wheel
        ? '车轮'
        : '配件';
    return '$cat +${bonus!.percent}%';
  }
}

// ========== 插槽常量 ==========
const s024 = SlotData(0, 2, 4);
const s121 = SlotData(1, 2, 1);
const s123 = SlotData(1, 2, 3);
const s131 = SlotData(1, 3, 1);
const s202 = SlotData(2, 0, 2);
const s203 = SlotData(2, 0, 3);
const s221 = SlotData(2, 2, 1);
const s222 = SlotData(2, 2, 2);
const s223 = SlotData(2, 2, 3);
const s232 = SlotData(2, 3, 2);
const s233 = SlotData(2, 3, 3);
const s321 = SlotData(3, 2, 1);
const s331 = SlotData(3, 3, 1);
const s322 = SlotData(3, 2, 2);
const s421 = SlotData(4, 2, 1);

// ========== 加成常量 ==========
const bBody10 = BonusData(PartCategory.body, 10);
const bBody20 = BonusData(PartCategory.body, 20);
const bWeapon10 = BonusData(PartCategory.weapon, 10);
const bWeapon15 = BonusData(PartCategory.weapon, 15);
const bWheel10 = BonusData(PartCategory.wheel, 10);
const bWheel15 = BonusData(PartCategory.wheel, 15);
const bWheel25 = BonusData(PartCategory.wheel, 25);
const bWheel50 = BonusData(PartCategory.wheel, 50);
const bGadget10 = BonusData(PartCategory.gadget, 10);
const bGadget20 = BonusData(PartCategory.gadget, 20);
const bGadget25 = BonusData(PartCategory.gadget, 25);

// ========== 数据库 ==========
class PartDatabase {
  static final List<PartData> allParts = _buildAllParts();
  static Map<PartCategory, List<PartData>>? _byCategory;

  static List<PartData> filterByCategory(PartCategory cat) {
    _byCategory ??= _buildIndex();
    return _byCategory![cat]!;
  }

  static Map<PartCategory, List<PartData>> _buildIndex() {
    final result = <PartCategory, List<PartData>>{};
    for (final cat in PartCategory.values) result[cat] = [];
    for (final p in allParts) result[p.category]!.add(p);
    return result;
  }

  static List<PartData> _buildAllParts() => [
    // ========== 车身 Bodies ==========
    // R6
    PartData(
      id: 'tubby_bus',
      name: 'Tubby Bus',
      nameZh: '肥猫巴士',
      nameJa: 'おデブバス',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 35825,
      power: 35,
      bonus: bWheel25,
      slots: s233,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'claw_rider',
      name: 'Claw Rider',
      nameZh: '利爪骑士',
      nameJa: 'クローライダー',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 45312,
      power: 35,
      bonus: bWeapon15,
      slots: s232,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'cool_ducky',
      name: 'Cool Ducky',
      nameZh: '酷酷鸭',
      nameJa: 'クールダック',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 52560,
      power: 35,
      bonus: bGadget10,
      slots: s123,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'iron_maiden',
      name: 'Iron Maiden',
      nameZh: '铁娘子',
      nameJa: 'アイアンメイデン',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 48120,
      power: 35,
      bonus: bWheel15,
      slots: s222,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'popsicle_beast',
      name: 'Popsicle Beast',
      nameZh: '冰棒野兽',
      nameJa: 'アイスキャンデー・ビースト',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 44713,
      power: 35,
      bonus: bWeapon10,
      slots: s421,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'phantom_circus',
      name: 'Phantom Circus',
      nameZh: '幻影马戏团',
      nameJa: 'ファントムサーカス',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 46088,
      power: 40,
      bonus: bGadget20,
      slots: s203,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'ram',
      name: 'R.A.M.',
      nameZh: 'R.A.M.',
      nameJa: 'R.A.M.',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 32568,
      power: 35,
      bonus: bWeapon10,
      slots: s331,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'schrodintech',
      name: 'Schrodintech',
      nameZh: '薛定谔科技',
      nameJa: 'シュレーディンテック',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 40329,
      power: 40,
      bonus: bGadget10,
      slots: s223,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'blossom_star',
      name: 'Blossom Star',
      nameZh: '繁花之星',
      nameJa: 'ブロッサムスター',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 40164,
      power: 35,
      bonus: bWeapon10,
      slots: s222,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'green_dragon',
      name: 'Green Dragon',
      nameZh: '绿龙',
      nameJa: 'グリーンドラゴン',
      category: PartCategory.body,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 48392,
      power: 35,
      bonus: bWeapon10,
      slots: s232,
      sip: StatsIncrementPattern.r6,
    ),
    // R5
    PartData(
      id: 'stingy_bandit',
      name: 'Stingy Bandit',
      nameZh: '尖刺强盗',
      nameJa: 'スティンギーバンディット',
      category: PartCategory.body,
      rarity: Rarity.r5,
      hp1: 21240,
      power: 35,
      bonus: bWeapon10,
      slots: s232,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'diamond_pig',
      name: 'Diamond Pig',
      nameZh: '钻石猪',
      nameJa: 'ダイヤモンドピッグ',
      category: PartCategory.body,
      rarity: Rarity.r5,
      hp1: 14160,
      power: 30,
      bonus: bWeapon10,
      slots: s322,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'golem',
      name: 'Golem',
      nameZh: '石巨人',
      nameJa: 'ゴーレム',
      category: PartCategory.body,
      rarity: Rarity.r5,
      hp1: 18880,
      power: 35,
      bonus: bWeapon10,
      slots: s222,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'metal_beast',
      name: 'Metal Beast',
      nameZh: '金属野兽',
      nameJa: 'メタルビースト',
      category: PartCategory.body,
      rarity: Rarity.r5,
      hp1: 18880,
      power: 30,
      bonus: bWheel50,
      slots: s222,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'purr_mobile',
      name: 'Purr-Mobile',
      nameZh: '咕噜战车',
      nameJa: 'ニャーモービル',
      category: PartCategory.body,
      rarity: Rarity.r5,
      hp1: 18880,
      power: 35,
      bonus: bWeapon10,
      slots: s222,
      sip: StatsIncrementPattern.r5,
    ),
    // R4
    PartData(
      id: 'flower_power',
      name: 'Flower Power',
      nameZh: '鲜花力量',
      nameJa: 'フラワーパワー',
      category: PartCategory.body,
      rarity: Rarity.r4,
      hp1: 25960,
      power: 30,
      slots: s421,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'stove',
      name: 'Stove',
      nameZh: '炉子',
      nameJa: 'ストーブ',
      category: PartCategory.body,
      rarity: Rarity.r4,
      hp1: 25960,
      power: 30,
      slots: s202,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'apocatlypse_bus',
      name: 'Apocatlypse Bus',
      nameZh: '猫咪天启巴士',
      nameJa: 'CATの黙示録バス',
      category: PartCategory.body,
      rarity: Rarity.r4,
      hp1: 16520,
      power: 25,
      slots: s222,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'wild_west_coach',
      name: 'Wild West Coach',
      nameZh: '狂野西部马车',
      nameJa: 'ワイルドウエストコーチ',
      category: PartCategory.body,
      rarity: Rarity.r4,
      hp1: 21240,
      power: 30,
      slots: s123,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'ufo',
      name: 'UFO',
      nameZh: '飞碟',
      nameJa: 'UFO',
      category: PartCategory.body,
      rarity: Rarity.r4,
      hp1: 16520,
      power: 30,
      slots: s123,
      sip: StatsIncrementPattern.r4,
    ),
    // R3
    PartData(
      id: 'paws_rover',
      name: 'Paws Rover',
      nameZh: '猫爪火星车',
      nameJa: '肉球探査車',
      category: PartCategory.body,
      rarity: Rarity.r3,
      hp1: 16520,
      power: 30,
      slots: s222,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'lantern',
      name: 'Lantern',
      nameZh: '灯笼',
      nameJa: '灯籠',
      category: PartCategory.body,
      rarity: Rarity.r3,
      hp1: 14160,
      power: 20,
      slots: s131,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'santas_sleigh',
      name: "Santa's Sleigh",
      nameZh: '圣诞老人的雪橇',
      nameJa: 'サンタのソリ',
      category: PartCategory.body,
      rarity: Rarity.r3,
      hp1: 16520,
      power: 25,
      slots: s222,
      sip: StatsIncrementPattern.r3,
    ),
    // R2
    PartData(
      id: 'corsair',
      name: 'Corsair',
      nameZh: '海盗船',
      nameJa: '海賊車',
      category: PartCategory.body,
      rarity: Rarity.r2,
      hp1: 14160,
      power: 20,
      slots: s121,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'fire_hazard',
      name: 'Fire Hazard',
      nameZh: '火焰危机',
      nameJa: 'ファイヤーハザード',
      category: PartCategory.body,
      rarity: Rarity.r2,
      hp1: 11800,
      power: 25,
      slots: s222,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'glacial_menace',
      name: 'Glacial Menace',
      nameZh: '冰川威胁',
      nameJa: 'グレイシャルメナス',
      category: PartCategory.body,
      rarity: Rarity.r2,
      hp1: 14160,
      power: 30,
      slots: s123,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'pig',
      name: 'Pig',
      nameZh: '猪',
      nameJa: 'ブタ',
      category: PartCategory.body,
      rarity: Rarity.r2,
      hp1: 18880,
      power: 15,
      slots: s221,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'land_bathyscaphe',
      name: 'Land Bathyscaphe',
      nameZh: '陆上型深海潜艇',
      nameJa: '陸上潜水艇',
      category: PartCategory.body,
      rarity: Rarity.r2,
      hp1: 15340,
      power: 25,
      slots: s222,
      sip: StatsIncrementPattern.r2,
    ),
    // R1
    PartData(
      id: 'cloud',
      name: 'Cloud',
      nameZh: '云朵',
      nameJa: '雲',
      category: PartCategory.body,
      rarity: Rarity.r1,
      hp1: 16520,
      power: 30,
      slots: s024,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'dozer',
      name: 'Dozer',
      nameZh: '推土机',
      nameJa: 'ドーザー',
      category: PartCategory.body,
      rarity: Rarity.r1,
      hp1: 11800,
      power: 20,
      slots: s121,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'cutter',
      name: 'Cutter',
      nameZh: '切割机',
      nameJa: 'カッター',
      category: PartCategory.body,
      rarity: Rarity.r1,
      hp1: 11800,
      power: 20,
      slots: s121,
      sip: StatsIncrementPattern.r1,
    ),

    // ========== 武器 Weapons ==========
    // R6
    PartData(
      id: 'mad_panda',
      name: 'Mad Panda',
      nameZh: '疯狂熊猫',
      nameJa: 'マッドパンダ',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 13000,
      power: -15,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'kitty_orb',
      name: 'Kitty Orb',
      nameZh: '小猫能量球',
      nameJa: 'キティオーブ',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 12675,
      mHp1: 35000,
      power: -10,
      partClass: PartClass.minion,
      bonus: bBody20,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'hairball_thrower',
      name: 'Hairball Thrower',
      nameZh: '毛球投掷机',
      nameJa: '毛玉シューター',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 9000,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'mystic_slime',
      name: 'Mystic Slime',
      nameZh: '神秘史莱姆',
      nameJa: '神秘のスライム',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 12740,
      power: -15,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'gumball_gun',
      name: 'Gumball Gun',
      nameZh: '口香糖枪',
      nameJa: 'ガムボール銃',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 10920,
      power: -15,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'eel',
      name: 'Electric Eel',
      nameZh: '电鳗',
      nameJa: 'デンキウナギ',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 10000,
      power: -10,
      partClass: PartClass.special,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'acid_alien',
      name: 'Acid Alien',
      nameZh: '强酸外星人',
      nameJa: 'アシッドエイリアン',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 9000,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'bats',
      name: 'Bats',
      nameZh: '蝙蝠',
      nameJa: 'コウモリ',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 8000,
      mHp1: 11000,
      power: -10,
      partClass: PartClass.minion,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'sea_monster',
      name: 'Sea Monster',
      nameZh: '海怪',
      nameJa: 'シーモンスター',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 10500,
      mHp1: 20000,
      power: -15,
      partClass: PartClass.minion,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'bento_drone',
      name: 'Bento Drone',
      nameZh: '便当无人机',
      nameJa: 'キャラ弁ドローン',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 9000,
      mHp1: 30000,
      power: -10,
      partClass: PartClass.minion,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'blazing_dragon',
      name: 'Blazing Dragon',
      nameZh: '烈焰巨龙',
      nameJa: 'ブレイジングドラゴン',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 12285,
      power: -10,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'kappa_drone',
      name: 'Kappa Drone',
      nameZh: 'KAPPA无人机',
      nameJa: 'カッパドローン',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 8000,
      mHp1: 11000,
      power: -10,
      partClass: PartClass.minion,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'mad_log',
      name: 'Mad Log',
      nameZh: '疯狂原木',
      nameJa: 'マッド丸太',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 7500,
      power: -5,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'space_drill',
      name: 'Space Drill',
      nameZh: '太空钻头',
      nameJa: 'スペースドリル',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 8000,
      power: -10,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'daruma_drone',
      name: 'Daruma Drone',
      nameZh: '达摩无人机',
      nameJa: 'ダルマドローン',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 8250,
      mHp1: 12600,
      power: -10,
      partClass: PartClass.minion,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'plasma_sentry',
      name: 'Plasma Sentry',
      nameZh: '等离子哨兵',
      nameJa: 'プラズマセントリー',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 4500,
      power: -5,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'robot_head',
      name: 'Robot Head',
      nameZh: '机器人头',
      nameJa: 'ロボットヘッド',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      atk1: 10000,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'sonic_bell',
      name: 'Sonic Bell',
      nameZh: '音铃',
      nameJa: 'ソニックベル',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 7500,
      power: -5,
      partClass: PartClass.ranged,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'spicy_barrage',
      name: 'Spicy Barrage',
      nameZh: '辛辣弹幕',
      nameJa: 'スパイシーバラージ',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      atk1: 9000,
      power: -5,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'water_trident',
      name: 'Water Trident',
      nameZh: '水纹三叉戟',
      nameJa: 'ウォータートライデント',
      category: PartCategory.weapon,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      atk1: 10000,
      power: -5,
      partClass: PartClass.melee,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6Legacy,
    ),
    // R5
    PartData(
      id: 'cat_drone',
      name: 'Cat Drone',
      nameZh: '猫咪无人机',
      nameJa: 'CATドローン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 6000,
      mHp1: 10000,
      power: -10,
      partClass: PartClass.minion,
      bonus: bWeapon15,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'diamond_carp',
      name: 'Diamond Carp',
      nameZh: '钻石鲤',
      nameJa: 'ダイヤモンドコイ',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 4000,
      power: -15,
      partClass: PartClass.autoAim,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'bbq_gun',
      name: 'BBQ Gun',
      nameZh: 'BBQ枪',
      nameJa: 'BBQガン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 4500,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'basketball_cannon',
      name: 'Basketball Cannon',
      nameZh: '篮球大炮',
      nameJa: 'バスケットボールキャノン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 2800,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bGadget25,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'double_catcus',
      name: 'Double Catcus',
      nameZh: '双头猫咪仙人掌',
      nameJa: 'ダブルネコサボテン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 3500,
      power: -10,
      partClass: PartClass.melee,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'gyro_spirit',
      name: 'Gyro Spirit',
      nameZh: '陀螺精神',
      nameJa: 'ジャイロスピリット',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 5500,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bWeapon15,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'horns_of_rage',
      name: 'Horns of Rage',
      nameZh: '愤怒之角',
      nameJa: '怒りのホーン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 4500,
      power: -10,
      partClass: PartClass.special,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'cat_mine',
      name: "Cat's Mine",
      nameZh: '猫咪地雷炮',
      nameJa: 'CAT地雷',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 3750,
      power: -10,
      partClass: PartClass.autoAim,
      bonus: bGadget20,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'popcorn_launcher',
      name: 'Popcorn Launcher',
      nameZh: '爆米花发射器',
      nameJa: 'ポップコーンランチャー',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 4500,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'salmon_cannon',
      name: 'Salmon Cannon',
      nameZh: '三文鱼大炮',
      nameJa: 'サーモンキャノン',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 3000,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'uncle_sam',
      name: 'Uncle Sam',
      nameZh: '山姆大叔',
      nameJa: 'アングル・サム',
      category: PartCategory.weapon,
      rarity: Rarity.r5,
      atk1: 3000,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    // R4
    PartData(
      id: 'meteo_shower',
      name: 'Meteo Shower',
      nameZh: '流星雨',
      nameJa: 'メテオシャワー',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 3500,
      power: -10,
      partClass: PartClass.autoAim,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'double_laser',
      name: 'Double Laser',
      nameZh: '双重激光',
      nameJa: 'ダブルレーザー',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 2500,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'root_whip',
      name: 'Root Whip',
      nameZh: '根茎之鞭',
      nameJa: 'ポイズンルート',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 4500,
      power: -10,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'golem_fist',
      name: 'Golem Fist',
      nameZh: '石巨人之拳',
      nameJa: 'ゴーレムフィスト',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 3750,
      power: -10,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'hearth',
      name: 'Hearth',
      nameZh: '壁炉',
      nameJa: 'ハース',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 4500,
      power: -10,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'hidden_claw',
      name: 'Hidden Claw',
      nameZh: '隐秘之爪',
      nameJa: '隠しクロー',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 5000,
      power: -15,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'sunflower',
      name: 'Sunflower',
      nameZh: '向日葵',
      nameJa: 'ヒマワリ',
      category: PartCategory.weapon,
      rarity: Rarity.r4,
      atk1: 3500,
      power: -5,
      partClass: PartClass.autoAim,
      sip: StatsIncrementPattern.r4,
    ),
    // R3
    PartData(
      id: 'blazing_mace',
      name: 'Blazing Mace',
      nameZh: '炽烈狼牙棒',
      nameJa: 'ブレイズメイス',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 2500,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'eye_of_death',
      name: 'Eye of Death',
      nameZh: '死亡之眼',
      nameJa: 'デスアイ',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 4500,
      power: -10,
      partClass: PartClass.autoAim,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'flamethrower',
      name: 'Flamethrower',
      nameZh: '火焰喷射器',
      nameJa: '火炎放射器',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 4500,
      power: -10,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'golden_carp',
      name: 'Golden Carp',
      nameZh: '锦鲤',
      nameJa: '金のコイ',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 2000,
      power: -15,
      partClass: PartClass.autoAim,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'santas_laser_bell',
      name: "Santa's Laser Bell",
      nameZh: '圣诞老人的激光铃铛',
      nameJa: 'サンタのレーザーベル',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 3000,
      power: -10,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'trombone_cannon',
      name: 'Trombone Cannon',
      nameZh: '长号大炮',
      nameJa: 'トロンボーンキャノン',
      category: PartCategory.weapon,
      rarity: Rarity.r3,
      atk1: 4000,
      power: -15,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r3,
    ),
    // R2
    PartData(
      id: 'spike_strike',
      name: 'Spike Strike',
      nameZh: '突刺',
      nameJa: 'スパイクストライク',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 3500,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'dozer_double_blade',
      name: 'Dozer Double Blade',
      nameZh: '双刃推土机',
      nameJa: 'ドーザーダブルブレード',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 3500,
      power: -10,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'dragon_mortar',
      name: 'Dragon Mortar',
      nameZh: '龙头炮',
      nameJa: 'ドラゴン迫撃砲',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 2800,
      power: -15,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'big_boy',
      name: 'Big Boy',
      nameZh: '大男孩',
      nameJa: 'ビッグボーイ',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 3500,
      power: -10,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'swift_laser',
      name: 'Swift Laser',
      nameZh: '迅捷激光',
      nameJa: 'スピードレーザー',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 2200,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'cutter_rocket',
      name: 'Cutter Rocket',
      nameZh: '火箭切割机',
      nameJa: 'カッターロケット',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 3000,
      power: -10,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'santas_double_rocket',
      name: "Santa's Double Rocket",
      nameZh: '圣诞老人的双火箭',
      nameJa: 'サンタのダブルロケット',
      category: PartCategory.weapon,
      rarity: Rarity.r2,
      atk1: 1750,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r2,
    ),
    // R1
    PartData(
      id: 'ice_cream_mace',
      name: 'Ice Cream Mace',
      nameZh: '冰激凌瓦斯',
      nameJa: 'アイスクリームこん棒',
      category: PartCategory.weapon,
      rarity: Rarity.r1,
      atk1: 2000,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'cutter_chainsaw',
      name: 'Cutter Chainsaw',
      nameZh: '链锯切割机',
      nameJa: 'カッターチェーンソー',
      category: PartCategory.weapon,
      rarity: Rarity.r1,
      atk1: 4000,
      power: -10,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'rotating_mega_drill_g19',
      name: 'Rotating Mega Drill G-19',
      nameZh: '旋转巨型钻头G-19',
      nameJa: '回転メガドリルG-19',
      category: PartCategory.weapon,
      rarity: Rarity.r1,
      atk1: 3500,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'rotating_hyperboloid_g27',
      name: 'Rotating Hyperboloid G-27',
      nameZh: '旋转双曲面G-27',
      nameJa: '回転ハイバーボロイドG-27',
      category: PartCategory.weapon,
      rarity: Rarity.r1,
      atk1: 2500,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r1,
    ),

    // ========== 车轮 Wheels ==========
    // R6
    PartData(
      id: 'sand_tire',
      name: 'Sand Tire',
      nameZh: '沙地轮',
      nameJa: 'サンドタイヤ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 20060,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6Legacy,
    ),
    PartData(
      id: 'death_scooter',
      name: 'Death Scooter',
      nameZh: '死亡滑板轮',
      nameJa: 'デススクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 9440,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'life_scooter',
      name: 'Life Scooter',
      nameZh: '生命滑板轮',
      nameJa: 'ライフスクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 9440,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'sand_scooter',
      name: 'Sand Scooter',
      nameZh: '沙地滑板轮',
      nameJa: 'サンドスクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 17700,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6Legacy,
    ),
    PartData(
      id: 'flower_hover',
      name: 'Flower Hover',
      nameZh: '鲜花悬浮器',
      nameJa: 'フラワーホバー',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 9440,
      atk1: 1200,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'onion_thruster',
      name: 'Onion Thruster',
      nameZh: '洋葱推进器',
      nameJa: 'オニオンスラスタ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 9440,
      atk1: 1200,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'maki_knob',
      name: 'Maki Knob',
      nameZh: '手卷旋钮轮',
      nameJa: '巻き寿司ノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 8260,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'naruto_knob',
      name: 'Naruto Knob',
      nameZh: '鱼板旋钮轮',
      nameJa: 'ナルトノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 8260,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'nigiri_knob',
      name: 'Nigiri Knob',
      nameZh: '寿司旋钮轮',
      nameJa: '握り寿司ノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 8260,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'shuttle_knob',
      name: 'Shuttle Knob',
      nameZh: '航天飞机旋钮轮',
      nameJa: 'シャトルノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 8260,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'space_knob',
      name: 'Space Knob',
      nameZh: '太空旋钮轮',
      nameJa: 'スペースノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 8260,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'big_pumpkin_wheel',
      name: 'Big Pumpkin Wheel',
      nameZh: '大南瓜车轮',
      nameJa: 'ビッグパンプキンホイール',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 8260,
      atk1: 1750,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'small_pumpkin_wheel',
      name: 'Small Pumpkin Wheel',
      nameZh: '小南瓜车轮',
      nameJa: 'スモールパンプキンホイール',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 7670,
      atk1: 1250,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'coconut_knob',
      name: 'Coconut Knob',
      nameZh: '椰子旋钮轮',
      nameJa: 'ココナットノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 9440,
      bonus: bGadget25,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'seashell_roller',
      name: 'Seashell Roller',
      nameZh: '海贝滚轮',
      nameJa: 'シーシェルローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 18880,
      bonus: bWeapon15,
      sip: StatsIncrementPattern.r6,
    ),
    // R5
    PartData(
      id: 'boost_scooter',
      name: 'Boost Scooter',
      nameZh: '加速滑板轮',
      nameJa: 'ブーストスクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 9440,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'diamond_slow_scooter',
      name: 'Diamond Slow Scooter',
      nameZh: '钻石慢速滑板轮',
      nameJa: 'ダイヤモンドスロースクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 6490,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'diamond_slow_roller',
      name: 'Diamond Slow Roller',
      nameZh: '钻石慢速滚轮',
      nameJa: 'ダイヤモンドスローローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 5900,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'bandit_knob',
      name: 'Bandit Knob',
      nameZh: '强盗旋钮轮',
      nameJa: 'バンディットノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 7080,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'boost_knob',
      name: 'Boost Knob',
      nameZh: '加速旋钮轮',
      nameJa: 'ブーストノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 7080,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'rogue_knob',
      name: 'Rogue Knob',
      nameZh: '流氓旋钮轮',
      nameJa: 'ローグノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 7080,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'stingy_knob',
      name: 'Stingy Knob',
      nameZh: '尖刺旋钮轮',
      nameJa: 'スティンギーノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 7080,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'golem_tracks',
      name: 'Golem Tracks',
      nameZh: '石巨人履带',
      nameJa: 'ゴーレム無限軌道',
      category: PartCategory.wheel,
      rarity: Rarity.r5,
      hp1: 7080,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    // R4
    PartData(
      id: 'train_double_roller',
      name: 'Train Double Roller',
      nameZh: '火车双辊',
      nameJa: 'トレインダブルローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r4,
      hp1: 7080,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'big_tank_tracks',
      name: 'Big Tank Tracks',
      nameZh: '大坦克履带',
      nameJa: 'ビッグタンクローリー',
      category: PartCategory.wheel,
      rarity: Rarity.r4,
      hp1: 7080,
      sip: StatsIncrementPattern.r4,
    ),
    // R3
    PartData(
      id: 'dragon_roller',
      name: 'Dragon Roller',
      nameZh: '龙辊',
      nameJa: 'ドラゴンローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r3,
      hp1: 5900,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'dragon_knob',
      name: 'Dragon Knob',
      nameZh: '龙旋钮',
      nameJa: 'ドラゴンノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r3,
      hp1: 5310,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'stiff_roller',
      name: 'Stiff Roller',
      nameZh: '坚硬滚轮',
      nameJa: 'スティッフローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r3,
      hp1: 5192,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'train_guide_knob',
      name: 'Train Guide Knob',
      nameZh: '火车导向旋钮轮',
      nameJa: 'トレインガイドノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r3,
      hp1: 5900,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'tank_tracks',
      name: 'Tank Tracks',
      nameZh: '坦克履带',
      nameJa: 'タンクローリー',
      category: PartCategory.wheel,
      rarity: Rarity.r3,
      hp1: 5900,
      sip: StatsIncrementPattern.r3,
    ),
    // R2
    PartData(
      id: 'santas_sticky_tire',
      name: "Santa's Sticky Tire",
      nameZh: '圣诞老人的粘性轮胎',
      nameJa: 'サンタのスティッキータイヤ',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 6560,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'anti_gravity_scooter_x19',
      name: 'Anti-Gravity Scooter X-19',
      nameZh: '反重力滑板车X-19',
      nameJa: '反重力スクーターX-19',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 5711,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'anti_gravity_scooter_x70',
      name: 'Anti-Gravity Scooter X-70',
      nameZh: '反重力滑板车X-70',
      nameJa: '反重力スクーターX-70',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 5711,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'ice_cream_truck_drive_scooter',
      name: 'Ice Cream Truck Drive Scooter',
      nameZh: '冰上滑行车',
      nameJa: 'アイスドライブスクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 5711,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'anti_gravity_roller',
      name: 'Anti-Gravity Roller',
      nameZh: '反重力滚轮',
      nameJa: '反重力ローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 5192,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'fire_engine_double_roller',
      name: 'Fire Engine Double Roller',
      nameZh: '火焰双辊',
      nameJa: 'ファイヤーダブルローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 5900,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'anti_gravity_knob',
      name: 'Anti-Gravity Knob',
      nameZh: '反重力旋钮轮',
      nameJa: '反重力ノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 4672,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'dozer_drive_knob',
      name: 'Dozer Drive Knob',
      nameZh: '推土机驱动柄',
      nameJa: 'ドーザーシフトノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r2,
      hp1: 4672,
      sip: StatsIncrementPattern.r2,
    ),
    // R1
    PartData(
      id: 'cutter_drive_bigfoot',
      name: 'Cutter Drive Bigfoot',
      nameZh: '大轮切割机',
      nameJa: 'カッタードライブビッグフット',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 7164,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'corsair_drive_tire',
      name: 'Corsair Drive Tire',
      nameZh: '海盗船驱动轮胎',
      nameJa: '海賊ドライブタイヤ',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5970,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'cutter_tire',
      name: 'Cutter Tire',
      nameZh: '切割机轮胎',
      nameJa: 'カッタータイヤ',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5970,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'coach_tire',
      name: 'Coach Tire',
      nameZh: '马车轱辘轮',
      nameJa: 'コーチタイヤ',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5970,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'ice_cream_truck_guide_scooter',
      name: 'Ice Cream Truck Guide Scooter',
      nameZh: '冰上导航滑行车',
      nameJa: 'アイスガイドスクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5192,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'slow_scooter',
      name: 'Slow Scooter',
      nameZh: '慢速滑板轮',
      nameJa: 'スロースクーター',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5192,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'corsair_guide_roller',
      name: 'Corsair Guide Roller',
      nameZh: '海盗船导辊',
      nameJa: '海賊ガイドローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 4720,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'fire_engine_guide_roller',
      name: 'Fire Engine Guide Roller',
      nameZh: '火焰导辊',
      nameJa: 'ファイヤーガイドローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 4720,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'slow_roller',
      name: 'Slow Roller',
      nameZh: '慢速滚轮',
      nameJa: 'スローローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 4720,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'santas_sticky_roller',
      name: "Santa's Sticky Roller",
      nameZh: '圣诞老人的粘辊',
      nameJa: 'サンタのスティッキーローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 4720,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'coach_roller',
      name: 'Coach Roller',
      nameZh: '马车滚轮',
      nameJa: '駅馬車ローラー',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 5192,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'dozer_guide_knob',
      name: 'Dozer Guide Knob',
      nameZh: '推土机导柄',
      nameJa: 'ドーザーガイドノブ',
      category: PartCategory.wheel,
      rarity: Rarity.r1,
      hp1: 4248,
      sip: StatsIncrementPattern.r1,
    ),

    // ========== 装置 Gadgets ==========
    // R6
    PartData(
      id: 'slug_snot',
      name: "Slug Snot",
      nameZh: '鼻涕虫黏液',
      nameJa: 'ナメクジの粘液',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 20072,
      power: 5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'coffee_cup',
      name: 'Coffee Cup',
      nameZh: '咖啡杯',
      nameJa: 'コーヒーカップ',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 16284,
      power: 5,
      partClass: PartClass.special,
      bonus: bWeapon15,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'deflecting_shield',
      name: 'Deflecting Shield',
      nameZh: '偏转盾牌',
      nameJa: '偏向シールド',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 16520,
      power: -10,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'enrager',
      name: 'Enrager',
      nameZh: '激怒器',
      nameJa: 'エンレイジャー',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 14632,
      power: -10,
      partClass: PartClass.special,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'geyser',
      name: 'Geyser',
      nameZh: '间歇泉',
      nameJa: 'ガイザー',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 18880,
      power: -5,
      partClass: PartClass.autoAim,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6Legacy,
    ),
    PartData(
      id: 'kitty_ghost',
      name: 'Kitty Ghost',
      nameZh: '猫咪鬼魂',
      nameJa: 'キティゴースト',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 16284,
      power: -5,
      partClass: PartClass.autoAim,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'healing_drone',
      name: 'Healing Drone',
      nameZh: '治疗无人机',
      nameJa: '回復ドローン',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 16284,
      mHp1: 32000,
      power: -5,
      partClass: PartClass.minion,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'hungry_hook',
      name: 'Hungry Hook',
      nameZh: '饥饿勾索',
      nameJa: 'ハングリーフック',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 14632,
      power: -5,
      partClass: PartClass.ranged,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'paralyzing_potion',
      name: 'Paralyzing Potion',
      nameZh: '麻痹药水',
      nameJa: 'しびれポーション',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 13334,
      power: -10,
      partClass: PartClass.ranged,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'squid_cannon',
      name: 'Squid Cannon',
      nameZh: '鱿鱼炮',
      nameJa: 'イカ大砲',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 20072,
      power: -10,
      partClass: PartClass.autoAim,
      bonus: bWheel10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'swapper',
      name: 'Swapper',
      nameZh: '交换器',
      nameJa: 'スワッパー',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.mecha,
      hp1: 19116,
      power: -5,
      partClass: PartClass.special,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'voodoo_doll',
      name: 'Voodoo Doll',
      nameZh: '巫毒娃娃',
      nameJa: 'ブードゥー人形',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.gluttony,
      hp1: 19116,
      power: -10,
      partClass: PartClass.special,
      bonus: bGadget10,
      sip: StatsIncrementPattern.r6,
    ),
    PartData(
      id: 'water_blaster',
      name: 'Water Blaster',
      nameZh: '水爆枪',
      nameJa: 'ウォーターブラスター',
      category: PartCategory.gadget,
      rarity: Rarity.r6,
      sponsor: Sponsor.naturalis,
      hp1: 19470,
      power: -5,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r6Legacy,
    ),
    // R5
    PartData(
      id: 'boxing_glove',
      name: 'Boxing Glove',
      nameZh: '拳击手套',
      nameJa: 'ボクシンググローブ',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 4720,
      power: -5,
      partClass: PartClass.melee,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'diamond_lotus',
      name: 'Diamond Lotus',
      nameZh: '钻石莲花',
      nameJa: 'ダイヤモンド蓮',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 4720,
      power: 5,
      partClass: PartClass.special,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'firework',
      name: 'Firework',
      nameZh: '烟花',
      nameJa: '花火',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 9440,
      power: -5,
      partClass: PartClass.autoAim,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'lifestone',
      name: 'Lifestone',
      nameZh: '生命石',
      nameJa: 'ライフストーン',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 9440,
      power: -10,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'rune_of_protection',
      name: 'Rune Of Protection',
      nameZh: '保护符文',
      nameJa: '守りのルーン',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 7080,
      power: -10,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'scrambler',
      name: 'Scrambler',
      nameZh: '扰频器',
      nameJa: 'スクランブラー',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 7080,
      power: -10,
      partClass: PartClass.special,
      bonus: bBody10,
      sip: StatsIncrementPattern.r5,
    ),
    PartData(
      id: 'stop_sign',
      name: 'Stop Sign',
      nameZh: '停止标志',
      nameJa: '停止標識',
      category: PartCategory.gadget,
      rarity: Rarity.r5,
      hp1: 4720,
      power: -10,
      partClass: PartClass.special,
      bonus: bWeapon10,
      sip: StatsIncrementPattern.r5,
    ),
    // R4
    PartData(
      id: 'flue',
      name: 'Flue',
      nameZh: '烟道',
      nameJa: 'フルー',
      category: PartCategory.gadget,
      rarity: Rarity.r4,
      hp1: 4720,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'skull_goblet',
      name: 'Skull Goblet',
      nameZh: '骷髅酒杯',
      nameJa: 'スカルゴブレット',
      category: PartCategory.gadget,
      rarity: Rarity.r4,
      hp1: 5900,
      power: -5,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r4,
    ),
    PartData(
      id: 'electric_lasso',
      name: 'Electric Lasso',
      nameZh: '带电套索',
      nameJa: '電気投げ縄',
      category: PartCategory.gadget,
      rarity: Rarity.r4,
      hp1: 4720,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r4,
    ),
    // R3
    PartData(
      id: 'electrified_barbed_wire',
      name: 'Electrified Barbed Wire',
      nameZh: '带电铁丝网',
      nameJa: '電流有刺鉄線',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 4720,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'energy_shield',
      name: 'Energy Shield',
      nameZh: '能量护盾',
      nameJa: 'エネルギーシルド',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 2360,
      power: -10,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'frost_sprinkler',
      name: 'Frost Sprinkler',
      nameZh: '制冷器',
      nameJa: 'フリーザー',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 4720,
      power: -15,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'lotus',
      name: 'Lotus',
      nameZh: '莲花',
      nameJa: '蓮',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 2360,
      power: 5,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'magic_lamp',
      name: 'Magic Lamp',
      nameZh: '魔法灯',
      nameJa: '魔法のランプ',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 2360,
      power: -5,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'nanobots_station',
      name: 'Nanobots Station',
      nameZh: '纳米机器人站',
      nameJa: 'ナノボットステーション',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 4720,
      power: -5,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r3,
    ),
    PartData(
      id: 'santas_freezing_gift',
      name: "Santa's Freezing Gift",
      nameZh: '圣诞老人的冷冻礼物',
      nameJa: 'サンタのフリージングギフト',
      category: PartCategory.gadget,
      rarity: Rarity.r3,
      hp1: 4720,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r3,
    ),
    // R2
    PartData(
      id: 'inverse_thruster',
      name: 'Inverse Thruster',
      nameZh: '反向推进器',
      nameJa: '逆スラスタ',
      category: PartCategory.gadget,
      rarity: Rarity.r2,
      hp1: 4720,
      power: 0,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'blasty_nudge',
      name: 'Blasty Nudge',
      nameZh: '爆裂推进器',
      nameJa: 'ブラストプッシュ',
      category: PartCategory.gadget,
      rarity: Rarity.r2,
      hp1: 4720,
      power: 0,
      partClass: PartClass.special,
      sip: StatsIncrementPattern.r2,
    ),
    PartData(
      id: 'lucky_horseshoe',
      name: 'Lucky Horseshoe',
      nameZh: '幸运马蹄铁',
      nameJa: '幸運の蹄鉄',
      category: PartCategory.gadget,
      rarity: Rarity.r2,
      hp1: 4720,
      power: -5,
      partClass: PartClass.autoAim,
      sip: StatsIncrementPattern.r2,
    ),
    // R1
    PartData(
      id: 'dozer_forklift',
      name: 'Dozer Forklift',
      nameZh: '推土机铲车',
      nameJa: 'ドーザーフォークリフト',
      category: PartCategory.gadget,
      rarity: Rarity.r1,
      hp1: 4720,
      power: 0,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'corsair_harpoon',
      name: 'Corsair Harpoon',
      nameZh: '海盗船鱼叉',
      nameJa: '海賊のハープーン',
      category: PartCategory.gadget,
      rarity: Rarity.r1,
      hp1: 4720,
      power: -5,
      partClass: PartClass.ranged,
      sip: StatsIncrementPattern.r1,
    ),
    PartData(
      id: 'cutter_repulse',
      name: 'Cutter Repulse',
      nameZh: '切割机反推器',
      nameJa: 'カッターリパルサー',
      category: PartCategory.gadget,
      rarity: Rarity.r1,
      hp1: 4720,
      power: -5,
      partClass: PartClass.melee,
      sip: StatsIncrementPattern.r1,
    ),
  ];
}

// ========== 升级费用表 ==========
/// [p] = 碎片 Pieces, [c] = 紫票 Cash, [t] = 代币 Token
/// 索引从 0 开始, [i] = 升到 i 级的总消耗
class UpgradeCostEntry {
  final int pieces;
  final int cash;
  final int token;
  const UpgradeCostEntry(this.pieces, this.cash, this.token);
}

const Map<Rarity, List<UpgradeCostEntry>> upgradeCosts = {
  Rarity.r1: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(2, 10, 0),
    UpgradeCostEntry(3, 50, 0),
    UpgradeCostEntry(4, 100, 0),
    UpgradeCostEntry(5, 150, 0),
    UpgradeCostEntry(6, 200, 0),
    UpgradeCostEntry(7, 300, 0),
    UpgradeCostEntry(8, 400, 0),
    UpgradeCostEntry(9, 600, 0),
    UpgradeCostEntry(14, 800, 0),
    UpgradeCostEntry(19, 2000, 0),
    UpgradeCostEntry(29, 5000, 0),
    UpgradeCostEntry(49, 15000, 0),
    UpgradeCostEntry(59, 20000, 0),
    UpgradeCostEntry(79, 25000, 10),
    UpgradeCostEntry(99, 30000, 12),
    UpgradeCostEntry(119, 35000, 14),
    UpgradeCostEntry(144, 40000, 16),
    UpgradeCostEntry(169, 45000, 18),
    UpgradeCostEntry(194, 50000, 20),
  ],
  Rarity.r2: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(1, 20, 0),
    UpgradeCostEntry(2, 100, 0),
    UpgradeCostEntry(3, 200, 0),
    UpgradeCostEntry(4, 300, 0),
    UpgradeCostEntry(5, 400, 0),
    UpgradeCostEntry(5, 600, 0),
    UpgradeCostEntry(5, 800, 0),
    UpgradeCostEntry(6, 1200, 0),
    UpgradeCostEntry(9, 1600, 0),
    UpgradeCostEntry(14, 4000, 0),
    UpgradeCostEntry(19, 8000, 0),
    UpgradeCostEntry(34, 25000, 0),
    UpgradeCostEntry(49, 32500, 0),
    UpgradeCostEntry(64, 40000, 20),
    UpgradeCostEntry(79, 47500, 24),
    UpgradeCostEntry(94, 55000, 28),
    UpgradeCostEntry(114, 62500, 32),
    UpgradeCostEntry(134, 70000, 36),
    UpgradeCostEntry(154, 77500, 40),
  ],
  Rarity.r3: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(1, 50, 0),
    UpgradeCostEntry(1, 250, 0),
    UpgradeCostEntry(1, 500, 0),
    UpgradeCostEntry(2, 750, 0),
    UpgradeCostEntry(2, 1000, 0),
    UpgradeCostEntry(2, 1500, 0),
    UpgradeCostEntry(2, 2000, 0),
    UpgradeCostEntry(3, 3000, 0),
    UpgradeCostEntry(4, 4000, 0),
    UpgradeCostEntry(5, 7500, 0),
    UpgradeCostEntry(7, 12500, 0),
    UpgradeCostEntry(14, 50000, 0),
    UpgradeCostEntry(24, 75000, 0),
    UpgradeCostEntry(34, 100000, 30),
    UpgradeCostEntry(44, 125000, 36),
    UpgradeCostEntry(54, 150000, 42),
    UpgradeCostEntry(69, 175000, 48),
    UpgradeCostEntry(84, 200000, 54),
    UpgradeCostEntry(99, 225000, 60),
  ],
  Rarity.r4: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(1, 1000, 0),
    UpgradeCostEntry(1, 1500, 0),
    UpgradeCostEntry(1, 2000, 0),
    UpgradeCostEntry(1, 2500, 0),
    UpgradeCostEntry(2, 5000, 0),
    UpgradeCostEntry(2, 7500, 0),
    UpgradeCostEntry(2, 10000, 0),
    UpgradeCostEntry(2, 15000, 0),
    UpgradeCostEntry(3, 20000, 0),
    UpgradeCostEntry(4, 30000, 0),
    UpgradeCostEntry(5, 50000, 0),
    UpgradeCostEntry(11, 100000, 0),
    UpgradeCostEntry(19, 135000, 0),
    UpgradeCostEntry(27, 170000, 40),
    UpgradeCostEntry(35, 205000, 48),
    UpgradeCostEntry(43, 240000, 56),
    UpgradeCostEntry(53, 275000, 64),
    UpgradeCostEntry(63, 310000, 72),
    UpgradeCostEntry(73, 345000, 80),
  ],
  Rarity.r5: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(1, 3000, 0),
    UpgradeCostEntry(1, 4500, 0),
    UpgradeCostEntry(1, 6000, 0),
    UpgradeCostEntry(1, 7500, 0),
    UpgradeCostEntry(2, 15000, 0),
    UpgradeCostEntry(2, 22500, 0),
    UpgradeCostEntry(2, 30000, 0),
    UpgradeCostEntry(2, 45000, 0),
    UpgradeCostEntry(2, 60000, 0),
    UpgradeCostEntry(3, 90000, 0),
    UpgradeCostEntry(3, 150000, 0),
    UpgradeCostEntry(7, 300000, 0),
    UpgradeCostEntry(11, 350000, 0),
    UpgradeCostEntry(13, 400000, 50),
    UpgradeCostEntry(15, 450000, 60),
    UpgradeCostEntry(17, 500000, 70),
    UpgradeCostEntry(22, 550000, 80),
    UpgradeCostEntry(27, 600000, 90),
    UpgradeCostEntry(32, 650000, 100),
  ],
  Rarity.r6: [
    UpgradeCostEntry(0, 0, 0),
    UpgradeCostEntry(1, 0, 0),
    UpgradeCostEntry(2, 8000, 0),
    UpgradeCostEntry(2, 12000, 0),
    UpgradeCostEntry(3, 16000, 0),
    UpgradeCostEntry(3, 25000, 1),
    UpgradeCostEntry(4, 30000, 4),
    UpgradeCostEntry(4, 50000, 8),
    UpgradeCostEntry(5, 75000, 13),
    UpgradeCostEntry(6, 125000, 19),
    UpgradeCostEntry(8, 175000, 26),
    UpgradeCostEntry(10, 250000, 34),
    UpgradeCostEntry(12, 325000, 43),
    UpgradeCostEntry(15, 425000, 53),
    UpgradeCostEntry(20, 525000, 64),
    UpgradeCostEntry(25, 650000, 76),
    UpgradeCostEntry(30, 800000, 89),
    UpgradeCostEntry(35, 900000, 103),
    UpgradeCostEntry(40, 1000000, 118),
  ],
};
